### ISSUE TITLE
(M) Account Authorization

### ISSUE THREAD

**Issue by mseaward** [peerplays-network/getscatter-walletpack#21]
### **Pre-requisites**

Account keys import will be a separate user story  that works in conjunction with the authorization function.

* [ ] #26 Account auth "import"
* [ ] #16 Create Account Screen (GUI)
* [x] #15 Create account backend

### **User Story**

Add functionality such that Scatter wallet, when using the Peerplays plugin, may authorize an account when provided with a username and password.

### **Impacts**

Describe which portion(s) of Peerplays that may be impacted by your request. Please tick at least one box.

* [X] API (the application programming interface)
* [ ] Build (the build process or something prior to compiled code)
* [ ] Deployment (the deployment process after building such as Docker, Gitlab, etc.)
* [X] Performance (system or user efficiency, etc.)
* [ ] Protocol (the blockchain logic, consensus, validation, etc.)
* [ ] Security (the security of system or user data, etc.)
* [ ] UX (the User Experience)
* [ ] Other (please add below)

## Community / PBSA check list

* [x] Evaluate / Prioritize Feature Request
* [x] Refine User Stories / Requirements
* [x] Define Test Cases
* [x] Design / Develop Solution
* [ ] Perform QA/Testing
* [ ] Update Documentation
